import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "@/components/Navigation";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Script src="https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.min.js"></Script>
        <Script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/836/OrbitControls.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/meshline@3.3.0/dist/index.min.js"></Script>
        <Script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/836/simplex-noise.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/variaboard@0.1.1/src/js/index.min.js"></Script>
        {/* <Script src="https://cdn.jsdelivr.net/npm/variaboard@0.1.1/src/js/util/calc.js"></Script> */}
        {children}
      </body>
    </html>
  );
}
